### ISSUE TITLE
Google Calendar: date not shown with all day events

### ISSUE THREAD

**Issue by ka8578** [pdincubus/JSONDerulo#21]
Hi,
first of all: thanks for this great snippet! 
However, I have problems with all day events. Their title is shown, but not the date ([[+eventStart]]). If it's an event with starting/ending time given (like 4-5pm), everything is OK.
Here's my snippet call:
<ul>
    [[!JSONDerulo?
        &feed=`googlecalendar`
        &tpl=`jd.googleCal-sas`
        &limit=`6`
        &feedLocation=`example@example.de`
        &apiKey=`12345`
    ]]
</ul>
and my chunk
<li class="cf">
[[+title:neq=`No events.`:then=`
<b>[[+eventStart:date=`%d.%m.%y`]]</b><br />
[[+title]]
`:else=`Momentan keine Termine.`]]
</li>
Regards
Chris

**Comment by andrewmfraser** [comment]
Chris,

Good catch. It looks like according to the Google Calendar API v3 that we have to look at the date field instead of datetime for recurring events:
```javascript
"start": {
    # Use date for all day event.
    "date": "startDate",
    # Use dateTime for a specific point in time.
    "dateTime": "startTime",
    "timeZone": "startTimeZone"
  },
  "end": {
    # Use date for all day event.
    "date": "endDate",
    # Use dateTime for a specific point in time.
    "dateTime": "endTime",
    "timeZone": "endTimeZone"
  }
```
Ref: https://developers.google.com/google-apps/calendar/migration

We can solve this using a simple if statement: if datetime is null then return date. My only concern is how it will display if your chunk normally shows time as well as date - this is something I'd like to test before patching. Can you screenshot how you're using it so I can better visualise it?

@pdincubus I can test and patch this week if you're cool with it?

**Comment by ka8578** [comment]
Hi,
thanks for the quick reply. I'm sorry that I don't know anything about the coding you mentioned, I just know a bit about html/css and that's it.
Anyway, I hope this sceenshot is what you meant:
![screenshot-alldayeventproblem](https://cloud.githubusercontent.com/assets/912182/6202868/8f2bb02e-b502-11e4-93ce-741f048c5bd1.jpg)
I haven't done any layout yet but you can see where I want to go. For the second event, our football night, the date is missing. For now, I just want to display date and title (and not the time). Maybe one day I might want to display time as well (if there is one) but not now.
Thanks

**Comment by pdincubus** [comment]
Be my guest - the calendar snippet is my least used part of the package, so it's not surprising I've missed out on all these V3 changes!

If 'date' is always filled in and so is 'datetime' for both start and end, we could just add additional placeholders so both are available all the time and then end users can choose what they want to output in their snippets?

[[+eventStart:default=`[[+eventAllDayStart]]`]] or something similar?

**Comment by andrewmfraser** [comment]
I've just created a PR to solve this, I had to add allDayEvent detection so that you can output the date the way you want.

@ka8578 here's the chunk I'm using on a client website thought it might be handy:

```php
<li class="cf">
[[+title:neq=`No events.`:then=`
  <h4>[[+allDayEvent:eq=`1`:then=`[[+eventStart:date=`%A %e %B`]]`:else=`[[+eventStart:date=`%A %e %B at %l:%M%P`]]`]]</h4>
  <h2><a href="[[+link]]" target="_blank">[[+title]]</a></h2>
`:else=`[[+title]]`]]
</li>
```

Let me know if you have any questions!

**Comment by ka8578** [comment]
GREAT! Thanks a lot! It's working ...
... although not 100% correctly. Title, date and time (if there is one) are shown correctly now (www.schule-am-sportpark.de). But if I click on the [[+link]], it shows a wrong time there (summer instead of winter time). But I guess that's a different problem/issue, maybe just a setting thing with my google calendar?
Anyway, thanks again.

**Comment by andrewmfraser** [comment]
Can you Paste the link it generates, I think it might be your Google Calendar Settings?

**Comment by ka8578** [comment]
Here's the link it generates: https://www.google.com/calendar/event?eid=bjJ1dTJlOGYzaDVxZTgxNnRhZnRodG41NzAgYS5rbmFwcEBzY2h1bGUtYW0tc3BvcnRwYXJrLmRl 
Here it says 12.15 although it should be 13.15 (as shown correctly with eventStart).

**Comment by andrewmfraser** [comment]
When I open it, it says:
Steuergruppe Schulentwicklung
Thu, 19 February, 13:15 – 15:15

Is that incorrect?

**Comment by ka8578** [comment]
No, that's correct. But why do I get the wrong time? 
In my calendar settings it says "GMT+01:00 Berlin" under "my current time zone". And that's correct. If I change this to "GMT+00:00" then all the times are incorrect. I don't get this ...

**Comment by andrewmfraser** [comment]
Hmm, open an Incognito Window and visit the link, if it's correct it's something to do with your Google Profile?

**Comment by ka8578** [comment]
opened the link in a chrome incognito window, stille 12.15 instead of 13.15

**Comment by andrewmfraser** [comment]
Ah when I opened in incognito it says 12:15 which is correct because if the event is at 13:15 GMT+1 then it is at 12:15 GMT which is what I'm looking at?

Regardless this is definitely an issue with Google Calendar not this plugin.

**Comment by ka8578** [comment]
Yep. I'll just leave out the link, I never really needed that anyway. Thanks again for your help!
