### ISSUE TITLE
Accentuated chars break hashtags

### ISSUE THREAD

**Issue by hitodev** [pdincubus/JSONDerulo#26]
Accents break twitter hashtags (French words).
May I suggest you to change Regex at line 900 in Snippet: JSONDerulo?

From:
$input= preg_replace('/(^|\s)#(\w+)/', '\1<a href="https://twitter.com/search?q=%23\2&src=hash">#\2</a>', $input);

To:
$input= preg_replace('/(^|\s)#(\w+)/u', '\1<a href="https://twitter.com/search?q=%23\2&src=hash">#\2</a>', $input);

Thanks for your extra!

**Comment by pdincubus** [comment]
Thanks for feedback, this should be sorted in v2.5.2 - soon to be on extras repo and already available on here!
