### ISSUE TITLE
Eventbrite change to API require expanded classes

### ISSUE THREAD

**Issue by apathyuk** [pdincubus/JSONDerulo#27]
Eventbrite have changed their API and expansions are now needed to get the extra fields.  See https://www.eventbrite.com/developer/v3/reference/expansions/

I added &expand=event,venue,ticket_classes to the feedUrl

**Comment by pdincubus** [comment]
Thanks for the heads up. This should be fixed in v2.5.4, commit [4023cfd1fb125cb30b194badfd27586f4c1ab5d3](https://github.com/pdincubus/JSONDerulo/commit/4023cfd1fb125cb30b194badfd27586f4c1ab5d3)
