### ISSUE TITLE
Twitter URLs aren't recognized within the [[+message]]

### ISSUE THREAD

**Issue by kehezen** [pdincubus/JSONDerulo#28]
As an example you can see http://franck-unrayondesoleil.com/index.php?id=3

On tweets that include an image, the t.co URL begins with http:// and gets wrapped.
On tweets including a pasted URL,  the t.co URL begins with https:// and does NOT get wrapped. 

Have I missed something ? Thanks for your answers...

**Comment by kehezen** [comment]
Ok it was time to learn...
As i'm using Twitter Faves, I changed line 981 
`$input= preg_replace("/(http:\/\/)(.*?)\/([\w\.\/\&\=\?\-\,\:\;\#\_\~\%\+]*)/", "<a href=\"\\0\">\\0</a>", $input);`
   
to
`$input= preg_replace("/(https|http:\/\/)(.*?)\/([\w\.\/\&\=\?\-\,\:\;\#\_\~\%\+]*)/", "<a href=\"\\0\">\\0</a>", $input);`

As i'm a total noob about this kind of... stuff... please let me know if I've done something wrong. Thanks

**Comment by pdincubus** [comment]
Thanks for the bug report, should be fixed by commit [754fa227e8b2a920938f9ba190ac8f8e69149bba](https://github.com/pdincubus/JSONDerulo/commit/754fa227e8b2a920938f9ba190ac8f8e69149bba)
