### ISSUE TITLE
instagram feed not working?

### ISSUE THREAD

**Issue by messyp** [pdincubus/JSONDerulo#29]
Am able to pull all other feed through apart from instagram - have followed instructions and created a client ID

Can you confirm if this is still working and how can i debug to see whats not pulling through correctly?

Thanks

**Comment by pdincubus** [comment]
Not used it for some time, but according to their changelog they introduced a bunch of new stuff before Christmas - https://www.instagram.com/developer/changelog/

I've not got time to look at this for a while, but I'm guessing it'll need some fixes to bring it inline with their current API stuff.

**Comment by pdincubus** [comment]
Having just tested a clean MODX install with latest JSONDerulo (2.5.4-pl) I can confirm this is still working correctly. You'll need to ensure you get the correct 'user ID' to get photos from, which is not the same as a username on Instagram. There are various tools out there to grab the user ID from a username - I checked mine with http://jelled.com/instagram/lookup-user-id
