### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by lkfranklin** [pdincubus/JSONDerulo#33]
Hi,

Is instagrams new API working in the latest version? I can't seem to get it to work.

Thanks,

**Comment by pdincubus** [comment]
Due to this: https://www.instagram.com/developer/changelog/
which will likely cause this: https://inbound.org/discuss/i-quit-instagram

I may just be removing the Instagram feed part altogether.

**Comment by lkfranklin** [comment]
Thanks for your reply.

I think I understand, do I take it from that then that you're awaiting review on submission and until then it won't work? 

Best,

**Comment by pdincubus** [comment]
No, quite the opposite - for you to use instagram through JSONDerulo, you have to get an API key (same as with Twitter and a few others) and in doing so are registering your own 'app' with them to allow you to access data via the API. With these changes, you start in sandbox mode and have very limited access then have to go through a review process before you can use it 'live'. Unless I'm missing something really obvious this pretty much means jumping through hoops unnecessarily. This being the case - it's not worth the pain even attempting it. I'll probably just remove the Instagram portion of JSONDerulo unless someone else wants to tackle it as I don't really have the time to investigate it properly any time soon!

Cheers

**Comment by lkfranklin** [comment]
Ah ok.. see I did think that at the start but when you go to submit your app for the API and it asks you what you intend to use it for and if you select 'I want to install a third party widget to show Instagram content on my website.' it does say the following:

'You do not need to submit for review for this use case. Some widgets may ask you to register a new client ID, but you should not submit it for review for the widget to work. Your client can remain in sandbox mode and the widget will have access to your last 20 media. If you are having issues with the widget, please contact the owner of the widget directly.'

So surely that means everything should  be fine? Unless I'm missing something obvious.

Thanks,

On a side note though this is a great extension!

**Comment by pdincubus** [comment]
It seems every request requires an access_token - which involves oAuth authentication and API keys and secrets and redirects to registered callback URLs. I've spent quite a while looking at getting this working even with workarounds and don't seem to be getting anywhere.

I double checked through the Instagram dev site and my 'client' doesn't need to be approved as in Sandbox mode I can fetch the latest 20 media in any stream I'm authorised to use with the API key and secret. Problem being that their documentation isn't all that helpful and I can't yet figure out why the access_token that Instagram give me when I authorise the 'client' doesn't let me actually fetch any media.

**Comment by lkfranklin** [comment]
No worries - thank you for all your hard work and investigation. I did manage to get it working ish using instafeedjs 

http://instafeedjs.com/


<script type="text/javascript" src="assets/js/instafeed.min.js"></script>
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: '[[*instaID]]',
        clientId: '[[*clientID]]',
        accessToken: '[[*instaAccess]]',
        template: '<li><img src="{{image}}" /></li>',
        resolution: 'standard_resolution'
    });
    userFeed.run();
</script>

Though of course like you say the client still needs the access token which can be generated by the client visiting: http://instagram.pixelunion.net/ after logging into instagram. You'll also need to get the userid by visiting this page: http://www.otzberg.net/iguserid/  

Bit messy...but it works.

**Comment by pdincubus** [comment]
Messy is what I was trying to avoid if possible - after some more investigation seems there may be a better oAuth2 lib I could use but that would involve far more time to get running and tested and packaged up than it's worth. For now, I'm probably just going to remove the Instagram portion and see if they sort themselves out at some point or I get a boat load of free time with nothing else more important to do! (Unlikely!)
