### ISSUE TITLE
How to create API key for Google Calendar?

### ISSUE THREAD

**Issue by vierkantemeter** [pdincubus/JSONDerulo#34]
Hi there,

Recently Google changed the way how to create an API key. I've tried to create all kinds of keys in the developer console, but I can't make the calendar to work. It worked fine just before the introduction of the key variable. Can anybody tell me how to create a key which can be used? I'm confused.

```
[[!JSONDerulo?
&feed=`googlecalendar`
&limit=`25`
&cacheTime=`1`
&cacheName=`kalender2`
&feedLocation=`domain.nl_ptoh6tdneg38cxxxxxxxx@group.calendar.google.com`
&apiKey=`AIzaSyCoSCfxxx-CHZU9uQpltuxxxxx`
&tpl=`google-calendar.feed.tpl`
]]
```

**Comment by dinglestein** [comment]
You got to make a API server key on there. I still can't seem to get any data to come through and the calendar is fully public too! Super annoying lol. Besides the Google Calendar one JSONderulo is a great extra.

**Comment by vierkantemeter** [comment]
Can anyone else confirm the problem is JSONDerlulo, and not a wrong API key?

**Comment by pdincubus** [comment]
I've just tested this and have it working using this call:

[[!JSONDerulo?
    &feed=`googlecalendar`
    &limit=`4`
    &feedLocation=`MYCALENDARID@group.calendar.google.com`
    &apiKey=`MYAPIKEY`
    &tpl=`jd.googleCalendar`
    &timeMin=`2011-06-03T10:00:00Z`
]]

It seems Google have changed their API stuff (again), so I made a new API key - type = Server on the API console:

https://console.developers.google.com/apis/credentials

If you want a quick way of testing the call, you can take the feed URL from the snippet and use it in your browser. Just replace the placeholders with the correct values:

https://www.googleapis.com/calendar/v3/calendars/{feedlocation}/events?key={apiKey}&orderBy=startTime&singleEvents=true&maxResults={limit}&minTime={timeMin}

**Comment by vierkantemeter** [comment]
I think I found the problem, line 360 in the snippet:
```
                    if ($event->$k == '') {
                        continue 2;
                    }
```

Because of the '2' it skipped the section below and the rawFeedData array was not filled. I removed the 2 and it worked again. Could it have something to do with my php version? (5.6)
