### ISSUE TITLE
Error when running two Twitter feeds on one web page

### ISSUE THREAD

**Issue by k9dug** [pdincubus/JSONDerulo#35]
I successfully set up a Twitter feed using the JSONDerulo snippet (2.6.0) in MODX (2.4.3). I wanted to show two separate Twitter feeds on the same page, so I created an app in the second Twitter account, created a new call to JSONDerulo with the new app details, tested it and it runs fine.

However, if I run both together on the same page, the page breaks: blank screen in FF, HTTP ERROR 500 in Chrome.

Checking my error log, I see:
 [-date-] [warn] [client -IP-] mod_fcgid: stderr: PHP Fatal error: Cannot redeclare sksort() (previously declared in /[site path]/httpdocs/core/cache/includes/elements/modsnippet/65.include.cache.php:740) in /[site path]/httpdocs/core/cache/includes/elements/modsnippet/65.include.cache.php on line 740 

I wrapped the sksort() function in the snippet in a conditional, as follows:
```
if (!function_exists('sksort')) {
   function sksort( &$array, $subkey, $sort_ascending ) {
      // Unaltered function code
      ...
   }
} 
```
and that solved the issue, at least to the extent that I am using the snippet (2x Twitter feeds).

Hope that's of help, but will be interested to know if there is a better way to call the snippet multiple times per page.

**Comment by pdincubus** [comment]
Thanks for this - I've added to the snippet and uploaded 2.6.1 onto the MODX Extras repo!

**Comment by k9dug** [comment]
Great! That was fast!
