### ISSUE TITLE
Noob Questions...

### ISSUE THREAD

**Issue by syberknight** [pdincubus/JSONDerulo#36]
sorry in advance if these questions are _too noob for you_, but i'm having a little trouble understanding / finding info/instructions on some of these things. i do know HTML/CSS. getting started learning JS/JQuery. & new to ModX Revo. so i _respectfully_ request your patience & acknowledgement on these things.

i'm trying to embed a **Tumblr** blog into a ModX site. before finding your modx addon, i was attempting to hack together whatever i could find using Jquery/Ajax & the Tumblr API. it's been a challenge to say the least. in hopes that this method would be easier & more efficient & flexible, i installed your addon & copied this code from your readme...
```
<ul>
    [[!JSONDerulo?
        &feed=`tumblr`
        &tpl=`jd.tumblr`
        &limit=`LIMIT`
        &cacheTime=`CACHE_TIME_IN_SECONDS`
        &cacheName=`UNIQUE_NAME_FOR_CACHE_FILE`
        &tag=`TAG TO FILTER BY`
        &postType=`POST TYPE TO FETCH`
        &notesInfo=`TRUE or FALSE`
        &blogUrl=`YOUR TUMBLR URL`
        &apiKey=`API KEY`
        &random=`1 OR 0`
    ]]
</ul>
```
...into a new page/resource.

**1) &limit -** i'm assuming this means "_how many posts to show/embed/get_". if so, no matter what number i put in there, it still pulls in all of them (which is only 13, because that's how many test tumblr posts i've made thus far). am i missing something here?

**2) &cache* -** i'm not understanding what these 2 properties mean. if it has anything to do with how often the feed is updated, i'd like it to show new blog posts immediately when made on tumblr.

**3) &blogUrl -** am i to include the "http://" part here, or just the "blogname.tumblr.com"?

_note: i "did" successfully go thru the steps to aquire the blog API KEY._

**4) &random -** does this mean to not have the posts sorted? if so, which does the 1/0 represent (assuming they represent Yes/No)? and if 'no', then hoping the sort order will be "_most recent on top_".

**5) STYLE -** is there a way to pull in the tumblr theme style with the feed?

**6) FLASH -** i did a tumblr blog post for each of the 'types' in an attempt to test all the options to make sure they come thru ok. i've noticed the "Audio" post embeds the audio in an old FLASH player. do you know how i can change this to be an HTML5 player instead?

**7) VIDEO -** i found why 1 youtube video was embedded 3 times of different sizes... can i make my own size for the embed by changing [[+player500]] to say [[+player450]] or other number?

**8) IMAGES -** since the images brought over is just the url to them, would i add the needed HTML/CSS in the tumblr Chunk file to have them be shown, or is there another method i'm not finding?

**9) LINKS -** link posts on tubmlr shows a preview image of the link; any way to get that brought over too?

**10) TYPES -** in looking at the tumblr chunk, it's only showing 5 of the 8 post types (missing Quote, Chat, & Answer). to add the other 3, would i (for example) copy the section for Text posts, then change the `eq=text` to `eq=quote`, and change +title to +text and +content to +source (& follow suite if more/less options)?

again, sorry for the length & beginner-level questions. if this is too absurd to answer, i understand. if not, i thank you for your time & expertise & kindness.
-jason.

**Comment by pdincubus** [comment]
Hi there,

So basically all the feeds in this extra just pull in what is made available by the respective API, and thus they are usually ordered by newest first. I'd had a request to randomise output some time ago so just set that to 1 to randomise the posts, or leave it out altogether if you don't - the default is no shuffling.

The limit is the number of posts to fetch.

The cache option tells MODX how long to cache the feed for - real time isn't really an option here as although Tumblr don't really tell you their API call limits, it's always best to not annoy them. If anybody wanted real time Tumblr feeds, it's best just to send them to the Tumblr!

Blog URL should be without http:// - I probably should have put that in the README. I will try to remember to the next time I make any changes.

The feed just fetches the JSON feed, so it's just a load of data - it doesn't fetch the theme of the site or anything like that. As with everything else in MODX, what's output on the front end is always controlled with chunks that you can then apply your own stylesheet to.

The type of embed that comes through is totally dependent on the source used in the Tumblr post. It's completely out of our control here. The same goes for videos - Vine, YouTube, Vimeo and uploaded videos to Tumblr all come out slightly differently! All the default chunk does is list a bunch of the stuff that's set as placeholders. The video size things are the only options that were available when I created this feed fetcher. As for making it a specific size on the frontend, it doesn't really matter which embed you use as you can style it to be any size you like.

For images, yes you'd need to change the chunk to do what you want, so stick it in an img element, run it through pThumb, etc. The default chunk is only there to get you started - you should duplicate it and change the markup to suit the site you're using it on.

Link type - again this is just what is sent by Tumblr. Just like Facebook does when you get URL previews, you'd probably need to set up some front end script to prefetch a preview of the sites.

For post types, the README says it's either all types or only one type. I know there are types missing, but I've never needed the others so far. It'd need some work in the PHP to set all the additional placeholders required for that. I'll get around to it at some point when I have the time!

Hope this helps!

**Comment by syberknight** [comment]
Hey, THANK YOU SO MUCH for your reply!!!

a couple clarifications please...

> The cache option tells MODX how long to cache the feed for - real time isn't really an option here as although Tumblr don't really tell you their API call limits, it's always best to not annoy them. If anybody wanted real time Tumblr feeds, it's best just to send them to the Tumblr!

so, do you have a recommended amount of time for this then?

> The type of embed that comes through is totally dependent on the source used in the Tumblr post. It's completely out of our control here.

i'm assuming this is also true for an Audio file (say, .mp3) that is uploaded to the Tumblr post rather than linked to from another source - right? if so, i'm just SO surprised that Tumblr is only offering an old FLASH player for these. would you know of any outside resources/links to point me to where i could investigate providing an HTML5 player instead? am google'ing it but not finding anything yet.

okay, thanks again for your help & your plugin!
-jason.

**Comment by pdincubus** [comment]
I did find something yesterday about their rate limits, but can't find it now. The rate limits are actually higher than I thought they were, but still not advisable to try 'real time'. The default for the snippet is 12 hours across the board, because different services have different limits so I just set a sensible default. I probably wouldn't set it much less than an hour (3600), but it's really up to you. The cacheName property is just to help you avoid filename conflicts if you're using multiple feeds on one page and isn't really required unless you're doing so.

All recent browsers have built-in audio and video players that will play most sensible formats, so if you can get a URL for the actual file and not a player embed code, you could maybe use that and just output it in a ```<audio>``` or ```<video>``` element in your chunk. I doubt that the API will just give you the bit you need though, it'd need more investigation!

**Comment by syberknight** [comment]
Thanks so much!

**Comment by pdincubus** [comment]
No problem!
