### ISSUE TITLE
Add Random property

### ISSUE THREAD

**Issue by benmarte** [pdincubus/JSONDerulo#6]
I think this extra could benefit from having a random functionality, for example in the FlickFeed snippet if I wanted to display a random image on a page each time it was loaded.

Something like &random=`1` that you can turn on or off.

Anyways keep up the good work the extra is awesome, just wish I could contribute more but my PHP skills are n00bish.

**Comment by pdincubus** [comment]
This might be a three-year old issue, and I've no idea why I didn't do it sooner... but v 2.6.0 has a random option. Only tested on Twitter basic feed and Google Calendar at the moment, but I've made the same change to all the feeds. Just pass &random=`1` to enable.
